### PR TITLE
Preserve semantic conflicts when git merges cleanly

### LINKED ISSUE #107: Same-named function added at different positions on both sides is silently duplicated (exit 0, no conflict markers)
## Summary

When both sides of a merge **add a function with the same name** but at **different anchor positions** and with **different bodies**, `weave` auto-resolves silently — `exit 0`, **no conflict markers**, nothing on stderr — and emits the function **twice**, producing output that does not compile (`Duplicate function implementation` / duplicate symbol). A genuine semantic conflict (two different bodies for the same function) is masked behind a clean auto-resolve.

This showed up repeatedly while using weave as the git merge driver during **stacked-branch rebases**, where the same function legitimately lands at a different line on each branch.

## Environment

- `weave 0.3.6` (Homebrew bottle), Linux
- Invoked as the git merge driver: `weave-driver %O %A %B %L %P`
- Reproduced directly with `weave-driver` on standalone files (no git needed)

## Minimal repro

```ts
// base.ts
function first() { return 1; }
function second() { return 2; }
```
```ts
// ours.ts  — adds computeKey BETWEEN first and second
function first() { return 1; }
function computeKey(input) { return input.id; }
function second() { return 2; }
```
```ts
// theirs.ts — adds computeKey AFTER second, with a DIFFERENT body
function first() { return 1; }
function second() { return 2; }
function computeKey(input) { return `${input.kind}:${input.id}`; }
```
```sh
cp ours.ts out.ts
weave-driver base.ts out.ts theirs.ts -o out.ts -p sample.ts ; echo "exit=$?"
```

**Actual:** `exit=0`, no conflict markers, `out.ts` contains `function computeKey` **twice** (the two different bodies, concatenated).

**Expected:** either flag a conflict (the bodies differ → a human should choose), or unify the entity — but never emit it twice.

## Why this looks like an entity-matching bug (not just line noise)

The neighbouring cases are handled **correctly**, which is what makes the duplicate surprising — weave clearly *can* reason about the entity, it just unifies by anchor position instead of by identity:

| ours vs theirs | result | correct? |
|---|---|---|
| same name, **same** position, **different** body | `exit=1`, conflict markers (``function `computeKey`: both added``) | ✅ |
| same name, **different** position, **identical** body | `exit=0`, **deduped to one** | ✅ |
| same name, **different** position, **different** body | `exit=0`, **silently duplicated** | ❌ this issue |

So the trigger is specifically *position-divergent + body-divergent*. It looks like same-named entities are bound to their surrounding anchors and then treated as two independent additions, rather than being unified by name/identity first (which would route them to either dedup or conflict).

## Impact

Silent, deterministic, and compile-breaking on the **auto-resolve happy path** (exit 0, no markers) — the one place a merge tool should never lose correctness, because the output gets `git add`-ed without review. It's easy to hit during stacked rebases. This is likely the same root-cause family as #24 (entity/import unification during auto-resolve).

### PR DESCRIPTION
**Pull request by edouard-andrei**
## Summary

Fixes #107 by preserving entity-level semantic conflicts when Git's line merge reports a clean result that would duplicate same-named divergent additions.

`weave` already resolved the issue case as a `BothAdded` semantic conflict, but the later marker-count floor replaced that conflict with `git merge-file` output whenever Git had fewer markers. In the issue repro, Git has zero markers because it silently emits both `computeKey` definitions, so the semantic conflict was erased.

This PR keeps the marker-count floor only when Git also reports conflict markers. Git-clean output can no longer mask an entity-level semantic conflict.

cc @rs545837

## Validation

- Direct `weave-driver` issue repro now exits `1` and reports `function computeKey: both added`.
- `cargo fmt --check`
- `cargo test -p weave-core`
- `cargo test --workspace`
- `cargo clippy --workspace --all-targets -- -D warnings`

### CODE REVIEW

**Comment by edouard-andrei** [comment]
Thanks @inspect-review — going through the findings:

### Findings 1 & 2 (same concern)

> when git merges cleanly (0 markers) but entity merge detects a semantic conflict (1+ markers), the semantic conflict will be silently discarded, contradicting the PR's stated goal

This reads the fall-through backwards — the code does the opposite. The early `return git_result` only fires when **both** halves of the condition hold:

```rust
if git_markers > 0 && entity_markers > git_markers {
    return git_result;
}
```

When git merges cleanly, `git_markers == 0`, so the condition is `false` and we do **not** return `git_result`. Control falls through to `return entity_result` at the end of the function (`merge.rs:728`), which carries the `BothAdded` conflict. The only other early return between here and there is gated on `entity_markers == 0`, so it's skipped in this case too. So the zero-marker case *is* handled — it's the default path, and it returns the semantic conflict.

Verified at runtime on the exact #107 repro (git concatenates both bodies with 0 markers; weave now keeps the conflict):

```
$ weave-driver base.ts out.ts theirs.ts -o out.ts -p sample.ts; echo "exit=$?"
weave: 1 conflict(s) in 'sample.ts'
  - function `computeKey`: both added
exit=1
```

This behavior is locked in by the new test `ts_same_named_function_added_at_different_positions_conflicts`.

The implicit-fall-through-vs-explicit-branch point is fair as a readability nit. I can add `if git_markers == 0 { return entity_result; }` or a clarifying comment so the zero-marker case is spelled out, but it's a no-op functionally.

### Finding 3 (`let content` truncation)

> This appears to be a display issue in the PR description rather than an actual code bug

Correct — it's a diff-rendering artifact, not source truncation. `cargo build`, `cargo clippy --workspace --all-targets -- -D warnings`, and `cargo test --workspace` all pass.
