### ISSUE TITLE
Same-named function added at different positions on both sides is silently duplicated (exit 0, no conflict markers)

### ISSUE THREAD

**Issue by edouard-andrei** [Ataraxy-Labs/weave#107]
## Summary

When both sides of a merge **add a function with the same name** but at **different anchor positions** and with **different bodies**, `weave` auto-resolves silently — `exit 0`, **no conflict markers**, nothing on stderr — and emits the function **twice**, producing output that does not compile (`Duplicate function implementation` / duplicate symbol). A genuine semantic conflict (two different bodies for the same function) is masked behind a clean auto-resolve.

This showed up repeatedly while using weave as the git merge driver during **stacked-branch rebases**, where the same function legitimately lands at a different line on each branch.

## Environment

- `weave 0.3.6` (Homebrew bottle), Linux
- Invoked as the git merge driver: `weave-driver %O %A %B %L %P`
- Reproduced directly with `weave-driver` on standalone files (no git needed)

## Minimal repro

```ts
// base.ts
function first() { return 1; }
function second() { return 2; }
```
```ts
// ours.ts  — adds computeKey BETWEEN first and second
function first() { return 1; }
function computeKey(input) { return input.id; }
function second() { return 2; }
```
```ts
// theirs.ts — adds computeKey AFTER second, with a DIFFERENT body
function first() { return 1; }
function second() { return 2; }
function computeKey(input) { return `${input.kind}:${input.id}`; }
```
```sh
cp ours.ts out.ts
weave-driver base.ts out.ts theirs.ts -o out.ts -p sample.ts ; echo "exit=$?"
```

**Actual:** `exit=0`, no conflict markers, `out.ts` contains `function computeKey` **twice** (the two different bodies, concatenated).

**Expected:** either flag a conflict (the bodies differ → a human should choose), or unify the entity — but never emit it twice.

## Why this looks like an entity-matching bug (not just line noise)

The neighbouring cases are handled **correctly**, which is what makes the duplicate surprising — weave clearly *can* reason about the entity, it just unifies by anchor position instead of by identity:

| ours vs theirs | result | correct? |
|---|---|---|
| same name, **same** position, **different** body | `exit=1`, conflict markers (``function `computeKey`: both added``) | ✅ |
| same name, **different** position, **identical** body | `exit=0`, **deduped to one** | ✅ |
| same name, **different** position, **different** body | `exit=0`, **silently duplicated** | ❌ this issue |

So the trigger is specifically *position-divergent + body-divergent*. It looks like same-named entities are bound to their surrounding anchors and then treated as two independent additions, rather than being unified by name/identity first (which would route them to either dedup or conflict).

## Impact

Silent, deterministic, and compile-breaking on the **auto-resolve happy path** (exit 0, no markers) — the one place a merge tool should never lose correctness, because the output gets `git add`-ed without review. It's easy to hit during stacked rebases. This is likely the same root-cause family as #24 (entity/import unification during auto-resolve).

**Comment by rs545837** [comment]
Thanks for mentioning this, I will fix this asap.
